app/models.py
from .extensions import db
from flask_login import UserMixin
from datetime import datetime

class Posts(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    content = db.Column(db.Text)
    date_posted = db.Column(db.DateTime, default= datetime.utcnow)
    slug = db.Column(db.String(255))
    poster_id= db.Column(db.Integer, db.ForeignKey('users.id'))

class Users(db.Model, UserMixin):
    id=db.Column(db.Integer, primary_key=True )
    username = db.Column(db.String(20), nullable=False, unique=True)
    name=db.Column(db.String(200), nullable=False)
    email=db.Column(db.String(120), nullable=False, unique=True)
    about_me=db.Column(db.Text(500), nullable=True)
    profile_pic=db.Column(db.String(120), nullable=True)
    date_added=db.Column(db.DateTime, default=datetime.utcnow)
    password_hash = db.Column(db.String(150))
    posts = db.relationship('Posts', backref='poster')

    # The serialize method converts the object to a dictionary
    def serialize(self):
        return {
            "id": self.id,
            "name": self.name,
            "emai": self.email
        }

app/__init__.py
from flask import Flask 
from flask_ckeditor import CKEditor
from flask_login import LoginManager, current_user
from app.public.webforms import SearchForm
from app.public import public_bp
from app.auth import auth_bp
from app.admin import admin_bp
from .extensions import db
from flask_migrate import Migrate
from .models import Users
db 
migrate = Migrate()
def create_app(config=None):
    app = Flask(__name__)
    if config is not None:
        app.config.from_object(config)
        ckeditor = CKEditor(app)
        app.register_blueprint(public_bp)
        app.register_blueprint(auth_bp)
        app.register_blueprint(admin_bp)
        db.init_app(app)
        migrate.init_app(app, db)
        with app.app_context():
            db.create_all()
        login_manager = LoginManager()
        login_manager.init_app(app)
        login_manager.login_view = 'auth.login'
        @login_manager.user_loader
        def load_user(user_id):
            return Users.query.get(int(user_id))
        @app.route('/favicon.ico')
        def favicon():
            return app.send_static_file('images/favicon.ico')
        @app.context_processor
        def inject_user():
            user = current_user  # Obtiene el usuario actual si está autenticado
            return dict(user=user)  # Pasamos el usuario al contexto global
        @app.context_processor
        def base():
            form = SearchForm()
            return dict(form=form)
        return app

app/admin/__init__.py
from flask import Blueprint
admin_bp = Blueprint('admin', __name__, template_folder="templates", static_folder="static")

from . import routes

app/admin/routes.py
from flask import render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from . import admin_bp


@admin_bp.route("/admin")
@login_required
def admin():
   id = current_user.id
   if id == 1:
      return render_template("admin/admin.html")
   else:
      flash("Sorry but you are not a admin")
      return redirect(url_for('auth.dashboard'))
   

app/templates/base.html
<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title%}{% endblock %}</title>
  <link rel="icon" href="{{ url_for('favicon') }}" type="image/x-icon">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="{{url_for('static', filename='css/custom.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}">
  {% block css %}{% endblock %}

</head>

<body>
  <header>
    {% block header %}
    {% endblock %}
  </header>
  <main>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  <footer>
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
    <script src="{{url_for('static', filename='js/base.js')}}"></script>
</body>

</html>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark myNavbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('public.index')}}">
      <img id="imageLoco" src="{{url_for('static', filename='images/mate.jpg')}}" alt="" width="60" height="60">
    </a>
    <a class="navbar-brand li_NavbarI" href="{{url_for('public.index')}}"><center>Enseñanza de la</center><center>Matemática</center></a>
      <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0 textNavbar">
              <li class="nav-item">
                  <a class="nav-link li_NavbarII" href="{{url_for('public.addPost')}}">Add Post</a>
              </li>
              {% if current_user.id == 1 %}
              <li class="nav-item">
                  <a class="nav-link li_NavbarII" href="{{url_for('admin.admin')}}">Admin</a>
              </li>
              {% endif %}
              
          </ul>
          <ul class="mx-auto">
            <form method="POST" action="{{url_for('public.search')}}" class="d-flex" role="search">
              {{ form.hidden_tag() }}
              <input class="form-control form-control-sm me-1" type="search" placeholder="Search" aria-label="Search" name="search" required>
              <button class="btn btn-info btn-sm" type="submit">Search</button>
            </form>
          </ul>
          <ul class="navbar-nav ms-auto">
            {% if current_user.is_authenticated %}
            <li   class="nav-item">
              <a class="nav-link li_NavbarIV" href="{{url_for('auth.dashboard', id=user.id)}}">Usuario: <span id="user" class="link li_NavbarII">{{user.username}}</span>
              
                <div id="myLink"></div>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link li_NavbarIV" href="{{url_for('auth.logout')}}">Logout</a>
            </li>

            {% else %}
            <li class="nav-item">
              <a class="nav-link li_NavbarIV" href="{{url_for('auth.login')}}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link li_NavbarIV" href="{{url_for('auth.sign')}}">Register</a>
            </li>

            {% endif %}
           
          </ul>


  </div>
</nav>

app/templates/search.html
<nav class="nav mt-1 ms-auto">
    <div class="container-fluid">
      <form class="d-flex" role="search">
        <input class="form-control-sm me-1" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success btn-sm" type="submit">Search</button>
      </form>
    </div>
  </nav>